import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from matplotlib.offsetbox import OffsetImage, AnnotationBbox
import os
from styles.company_style import COMPANY_STYLE

# Fake data (simulating Analysis Agent output)
data = [
    {"Name": "Rock", "track_count": 1297},
    {"Name": "Latin", "track_count": 579},
    {"Name": "Metal", "track_count": 374},
    {"Name": "Jazz", "track_count": 130},
    {"Name": "Blues", "track_count": 81},
]

x_values = [row["Name"] for row in data]
y_values = [row["track_count"] for row in data]

style = COMPANY_STYLE

# Create figure
fig, ax = plt.subplots(figsize=style["figure_size"])
fig.patch.set_facecolor(style["background_color"])
ax.set_facecolor(style["background_color"])

# Create gradient header bar at top
header_ax = fig.add_axes([0, 0.93, 1, 0.08])
header_ax.set_xlim(0, 1)
header_ax.set_ylim(0, 1)

# Gradient from teal to cyan
from matplotlib.colors import LinearSegmentedColormap
gradient = plt.cm.colors.LinearSegmentedColormap.from_list(
    "prosus_gradient", 
    [style["colors"][1], style["colors"][2]]
)
gradient_data = [[i/100 for i in range(100)]]
header_ax.imshow(gradient_data, aspect="auto", cmap=gradient, extent=[0, 1, 0, 1])
header_ax.axis("off")

# Bar colors - teal/cyan alternating, top bar in Prosus blue
bar_colors = [style["colors"][0]]  # First bar in Prosus blue (highlight)
for i in range(1, len(data)):
    bar_colors.append(style["colors"][1] if i % 2 == 0 else style["colors"][2])

# Create bars
bars = ax.bar(x_values, y_values, color=bar_colors, edgecolor="white", linewidth=1.5)

# Title in Prosus blue
ax.set_title(
    "Top 5 Genres by Track Count", 
    fontsize=style["title_size"], 
    fontweight="bold",
    color=style["text_color"],
    pad=20,
    loc="left"
)

ax.set_xlabel("Genre", fontsize=style["label_size"], color=style["axis_color"])
ax.set_ylabel("Track Count", fontsize=style["label_size"], color=style["axis_color"])

# Style axes
ax.tick_params(colors=style["axis_color"], labelsize=style["tick_size"])
ax.spines["bottom"].set_color(style["grid_color"])
ax.spines["left"].set_color(style["grid_color"])
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

# Grid
if style["grid"]:
    ax.yaxis.grid(True, color=style["grid_color"], alpha=style["grid_alpha"], linestyle="--")
    ax.set_axisbelow(True)

plt.xticks(rotation=0, ha="center")

# Value labels on bars
for bar, val in zip(bars, y_values):
    ax.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 25,
        f"{val:,}",
        ha="center",
        va="bottom",
        color=style["text_color"],
        fontsize=11,
        fontweight="bold"
    )

# Add logo if exists
if os.path.exists(style["logo_path"]):
    logo = mpimg.imread(style["logo_path"])
    logo_ax = fig.add_axes([0.85, 0.93, style["logo_size"], style["logo_size"] * 0.5])
    logo_ax.imshow(logo)
    logo_ax.axis("off")
    print("✅ Logo added")
else:
    print("Logo file not found")

# Add subtle footer
fig.text(
    0.99, 0.02,
    "Generated by Prosus AI Data Agent",
    fontsize=8,
    color=style["axis_color"],
    ha="right",
    alpha=0.6
)

# Adjust layout
plt.subplots_adjust(top=0.85, bottom=0.15)

# Ensure output directory exists
os.makedirs("output", exist_ok=True)

# Save
output_path = "output/prosus_style_chart.png"
plt.savefig(
    output_path, 
    dpi=style["dpi"], 
    bbox_inches="tight",
    facecolor=style["background_color"]
)
plt.show()

print(f"✅ Chart saved to {output_path}")